### ISSUE TITLE
Getting error on create account

### ISSUE THREAD

**Issue by SynomanBarris** [detronetdip/E-commerce#12]
There is an error "Something went wrong" each time I try to create an account on my local host, what might be wrong?

**Comment by SynomanBarris** [comment]
User account...am using it on my local host...what might be the problem?

**Comment by SynomanBarris** [comment]
Infact realised it's both

**Comment by detronetdip** [comment]
Have you created the database?

**Comment by SynomanBarris** [comment]
Yes. .and it's connected since I can login to admin

**Comment by SynomanBarris** [comment]
Fixed, was a problem with my code. Thanks for assistance
