### ISSUE TITLE
Error When Creating an Account

### ISSUE THREAD

**Issue by nazimboudeffa** [detronetdip/E-commerce#6]
Why when I try to create an account it asks me to enter the name ?

![kNgkevOusb](https://user-images.githubusercontent.com/1375686/177015555-5ed2dbbf-9633-44ad-b8d8-02fedc42a330.png)

**Comment by detronetdip** [comment]
This is a basic functionality.

**Comment by nazimboudeffa** [comment]
I mean even if I enter them

**Comment by detronetdip** [comment]
This is user account or seller account?

**Comment by nazimboudeffa** [comment]
It just worked locally with the update, I need to test it on the deployed site
