### ISSUE TITLE
can you kindly tell me admin password, i have changed from adminpanel admin password but still invalid

### ISSUE THREAD

**Issue by ScorpionGuzel** [detronetdip/E-commerce#8]
can you kindly tell me admin password, i have changed from adminpanel admin password but still invalid

**Comment by detronetdip** [comment]
@ScorpionGuzel I don't remember there is a way to change admin password from admin panel or not. BTW for admin 
USERNAME: `admin@gmail.com`
PASSWORD: `admin`

Thank you.

**Comment by detronetdip** [comment]
@ScorpionGuzel  If it has resolved your issue please close this.
